/**
 * Locked SEO URL maps — must match legacy .htaccess + setup_seo_urls.php exactly.
 * Changing these without 301 planning will hurt rankings.
 */

export const SITE_URL = "https://yildizhesap.net";
export const SITE_NAME = "yildizhesap.net - Hesap Satış Platformu";

/** categoryId → seo_slug */
export const CATEGORY_SEO_SLUGS: Readonly<Record<number, string>> = {
  7: "ana-hesaplar-dogrulanmis",
  8: "direncli-hesaplar",
  12: "old-accounts",
  13: "business-manager",
  14: "facebook-marketplace",
  15: "facebook-hesaplari",
  16: "instagram-hesaplari",
  20: "onayli-twitter-hesaplari",
  21: "tiktok-hesaplari",
  22: "mail-gmail-outlook-hotmail-hesaplari",
  27: "telegram-hesaplari",
} as const;

/** accountId → seo_slug */
export const PRODUCT_SEO_SLUGS: Readonly<Record<number, string>> = {
  12: "rastgele-kimlik-dogrulanmis-super-eski-facebook-hesabi-2015",
  13: "rastgele-kimlik-dogrulanmis-eski-facebook-hesabi-2010",
  14: "rastgele-kimlik-dogrulanmis-super-eski-facebook-hesabi-2010-2020",
  15: "rastgele-kimlik-dogrulanmis-eski-facebook-hesabi-2010-2023",
  16: "vietnam-kimligi-dogrulanmis-eski-facebook-hesabi-2024",
  17: "vietnam-kimligi-dogrulanmis-eski-facebook-hesabi-2023-2024",
  18: "vietnamda-yeniden-acilan-eski-facebook-hesabi-2024",
  19: "vietnamese-reinstated-aged-fb-account-2024",
  20: "random-reinstated-aged-fb-account-2010-2023",
  21: "random-reinstated-super-aged-fb-account-2007-2015",
  26: "poland-old-fb-account-2008-2021",
  27: "taiwan-old-fb-account",
  28: "uk-old-fb-account",
  29: "usa-old-fb-account-2024",
  30: "random-country-fb-account-can-create-sub-profile",
  31: "india-aged-fb-account",
  35: "250-dolar-limitli-tekli-business-manager-hesaplari",
  36: "kisittan-donmus-business-manager-hesaplari",
  37: "dogrulanmis-business-manager-hesaplari-3lu",
  38: "eski-business-manager-hesaplari",
  39: "business-manager-hesaplari",
  40: "gunluk-harcama-250-dolar-limitli-tekli-kisisel-reklam-hesabi",
  41: "facebook-marketplace-hesaplari",
  42: "kimlik-onayli-facebook-hesaplari",
  43: "kimlik-onayli-facebook-hesaplari-guclendirilmis",
  44: "facebook-hesaplari-turk",
  45: "facebook-hesaplari-yabanci",
  46: "instagram-hesaplari-10000-takipcili",
  47: "instagram-hesaplari-5000-takipcili",
  49: "20-adet-gonderili-instagram-hesaplari",
  50: "tanitim-onayli-instagram-hesaplari",
  60: "dogrulanmis-telegram-hesap",
  // Businesshesap.com catalog (source id + 1000).
  1001: "facebook-instagram-reklamlariniz-acilir",
  1002: "satilik-instagram-hesaplari",
  1003: "business-manager-satin-al",
  1004: "eski-business-manager-satin-al",
  1005: "facebook-hesaplari-paket-3",
  1006: "facebook-hesaplari-kimlik-onayli",
  1007: "5li-business-manager-satin-al",
  1008: "satilik-eski-facebook-sayfalari-satin-al",
  1009: "organik-yorum-hizmeti",
  1010: "facebook-hesaplari-turk-1-paket",
  1011: "facebook-hesaplari-turk-2-paket",
  1012: "onaylacom-smsonayservisi",
  1013: "discort-hesap-satin-al",
  1014: "instagram-hesaplari-1000-takipcili",
  // 1015 & 1016 dropped: same slugs as legacy 47 & 46 (5k/10k Instagram).
  1017: "tanitim-onayli-instagram-hesaplari-bh",
  1018: "onayli-gmail-hesaplari",
  1019: "onayli-x-hesaplari-satin-al",
  1020: "outlook-hesaplari",
  1021: "tiktok-hesaplari",
  1022: "satilik-telegram-hesaplari",
  1023: "dogrulanmis-business-manager-hesaplari-bh",
  1024: "5li-business-manager-satin-al-bh",
  1025: "gunluk-250dolar-limitli-tekli-kisisel-reklam-hesaplari",
  1026: "facebook-reklam-hesabi-kisisel-10lu",
  1027: "facebook-marketplace-hesap-satin-al",
  1028: "kisittan-donmus-business-manager",
  1029: "250usd-tekli-business-manager",
  1030: "facebook-30-60-li-reklam-hesabi-satin-al",
  1031: "dogrulanmis-business-manager-5li",
  1032: "gonderili-instagram-hesaplari",
  1033: "2012-tarihli-instagram-hesap-al",
  1034: "mavi-tik-alinan-instagram-hesaplari",
  1035: "10-adet-gonderili-instagram-hesaplari-eski",
  1036: "gonderili-instagram-hesaplari-1-4",
  1037: "harcama-yapmis-facebook-hesaplari-sayfali",
  1038: "reklam-erisimi-eklenmis-facebook-hesaplari",
  1039: "ads-aktif-mail-onayli-sayfali-facebook-hesaplari",
} as const;

/** Static SEO routes from router.php */
export const STATIC_SEO_ROUTES = [
  "siparis-takip",
  "tum-hesaplar",
  "sikca-sorulan-sorular",
  "hizmetler",
  "iletisim",
  "kvkk",
  "giris-yap",
  "kayit-ol",
  "gizlilik-politikasi",
  "kullanim-kosullari",
  "cerez-politikasi",
  "iade-politikasi",
  "hakkimizda",
] as const;
